# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasApplied',
            field=models.BooleanField(default=False),
        ),
    ]
