# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_user_hasapplied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='openDate',
        ),
        migrations.AddField(
            model_name='position',
            name='positionOpen',
            field=models.BooleanField(default=False),
        ),
    ]
