# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('fName', models.CharField(max_length=15)),
                ('lName', models.CharField(max_length=15)),
                ('admin', models.BooleanField(default=False)),
                ('hasApplied', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ALevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('dateSubmitted', models.DateField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications_ALevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('alevelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.ALevel')),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Applications_Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('lengthOfEmployment', models.CharField(max_length=30)),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Applications_Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField()),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Applications_Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.IntegerField()),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Applications_Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Applications_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.IntegerField()),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Applications_Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('applicationID', models.ManyToManyField(through='controller.Applications_Employment', to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('applicationID', models.ManyToManyField(through='controller.Applications_Hobbies', to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('applicationID', models.ManyToManyField(through='controller.Applications_Languages', to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=20)),
                ('positionDescription', models.CharField(max_length=50)),
                ('positionOpen', models.BooleanField(default=False)),
                ('deadlineDate', models.DateField()),
                ('applicationID', models.ManyToManyField(through='controller.Applications_Positions', to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=30)),
                ('applicationID', models.ManyToManyField(through='controller.Applications_Skills', to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('applicationID', models.ManyToManyField(through='controller.Applications_Universities', to='controller.Application')),
            ],
        ),
        migrations.AddField(
            model_name='applications_universities',
            name='universityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.University'),
        ),
        migrations.AddField(
            model_name='applications_skills',
            name='skillID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Skill'),
        ),
        migrations.AddField(
            model_name='applications_positions',
            name='positionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Position'),
        ),
        migrations.AddField(
            model_name='applications_languages',
            name='languageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Language'),
        ),
        migrations.AddField(
            model_name='applications_hobbies',
            name='hobbyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Hobby'),
        ),
        migrations.AddField(
            model_name='applications_employment',
            name='companyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Company'),
        ),
        migrations.AddField(
            model_name='alevel',
            name='applicationID',
            field=models.ManyToManyField(through='controller.Applications_ALevel', to='controller.Application'),
        ),
    ]
