# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('fName', models.CharField(max_length=15)),
                ('lName', models.CharField(max_length=15)),
                ('admin', models.BooleanField(default=False)),
                ('hasApplied', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ALevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('dateSubmitted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'submitted', b'Submitted'), (b'interview', b'Interview'), (b'rejected', b'Rejected'), (b'accepted', b'Accepted')], default=b'submitted', max_length=10)),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreeTitle', models.CharField(max_length=50)),
                ('degreeGrade', models.CharField(max_length=50)),
                ('degreeType', models.CharField(max_length=50)),
                ('universityName', models.CharField(max_length=50)),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('expertise', models.IntegerField()),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=20)),
                ('positionDescription', models.TextField()),
                ('positionOpen', models.BooleanField(default=False)),
                ('deadlineDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('jobTitle', models.CharField(max_length=30)),
                ('lengthOfEmployment', models.DurationField()),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('proficiency', models.IntegerField()),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('expertise', models.IntegerField()),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='positionID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Positions'),
        ),
        migrations.AddField(
            model_name='application',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alevels',
            name='applicationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Application'),
        ),
    ]
