# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Positions'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='positionOpen',
            field=models.BooleanField(default=True),
        ),
    ]
