# Generated by Django 2.1.7 on 2019-03-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20190306_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='feedback',
            field=models.CharField(default='No feedback available', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Being Reviewed', 'Being Reviewed'), ('Requested Interview', 'Requested Interview'), ('Interviewed', 'Interview'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Submitted', max_length=20),
        ),
    ]
